// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoBar.OrderOperations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.OrderOperations.Migrations
{
    [DbContext(typeof(OrderOperationsDbContext))]
    [Migration("20260905055531_AddLiquidation")]
    partial class AddLiquidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("order_operations")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoBar.OrderOperations.ConfirmationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("ConfirmedContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmed_context");

                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_confirmation_history");

                    b.HasIndex("IncorporationId")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_confirmation_history_incorporation");

                    b.ToTable("confirmation_history", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_confirmation_history_context_not_empty", "length(btrim(confirmed_context)) > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<int>("ContentOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("content_ordinal");

                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ResultDeliveredQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_delivered_quantity");

                    b.Property<Guid>("ResultHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_history_id");

                    b.Property<DateTimeOffset>("ResultOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_occurred_at");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_order_operations_delivery_commands");

                    b.HasIndex("ResultHistoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_delivery_commands_history");

                    b.HasIndex("IncorporationId", "ContentOrdinal")
                        .HasDatabaseName("IX_delivery_commands_content");

                    b.ToTable("delivery_commands", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_delivery_commands_content_ordinal_positive", "content_ordinal > 0");

                            t.HasCheckConstraint("CK_delivery_commands_kind_not_empty", "length(btrim(command_kind)) > 0");

                            t.HasCheckConstraint("CK_delivery_commands_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_delivery_commands_result_non_negative", "result_delivered_quantity >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<int>("ContentOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("content_ordinal");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_kind");

                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ResultingDeliveredQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_delivered_quantity");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_delivery_history");

                    b.HasIndex("IncorporationId", "ContentOrdinal", "OccurredAt", "Id")
                        .HasDatabaseName("IX_delivery_history_content_time_id");

                    b.ToTable("delivery_history", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_delivery_history_content_ordinal_positive", "content_ordinal > 0");

                            t.HasCheckConstraint("CK_delivery_history_event_kind_not_empty", "length(btrim(event_kind)) > 0");

                            t.HasCheckConstraint("CK_delivery_history_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_delivery_history_result_non_negative", "resulting_delivered_quantity >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryState", b =>
                {
                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<int>("ContentOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("content_ordinal");

                    b.Property<int>("DeliveredQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("delivered_quantity");

                    b.HasKey("IncorporationId", "ContentOrdinal")
                        .HasName("PK_order_operations_delivery_states");

                    b.ToTable("delivery_states", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_delivery_states_delivered_non_negative", "delivered_quantity >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("IntentContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_context");

                    b.Property<Guid>("ResultIncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_incorporation_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_order_operations_first_confirmation_commands");

                    b.HasIndex("ResultIncorporationId")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_first_confirmation_commands_result_incorporation");

                    b.ToTable("first_confirmation_commands", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_first_confirmation_commands_context_not_empty", "length(btrim(intent_context)) > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommandContent", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("LineOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("line_ordinal");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IdempotencyKey", "LineOrdinal")
                        .HasName("PK_order_operations_first_confirmation_command_contents");

                    b.ToTable("first_confirmation_command_contents", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_first_command_contents_ordinal_positive", "line_ordinal > 0");

                            t.HasCheckConstraint("CK_order_operations_first_confirmation_command_contents_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.Incorporation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_incorporations");

                    b.HasIndex("OrderId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_incorporations_order_ordinal");

                    b.ToTable("incorporations", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_incorporations_ordinal_positive", "ordinal > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.IncorporationContent", b =>
                {
                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<int>("ContentOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("content_ordinal");

                    b.Property<decimal>("AppliedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("applied_price");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresPreparationAtConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_preparation_at_confirmation");

                    b.HasKey("IncorporationId", "ContentOrdinal")
                        .HasName("PK_order_operations_incorporation_contents");

                    b.ToTable("incorporation_contents", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_incorporation_contents_ordinal_positive", "content_ordinal > 0");

                            t.HasCheckConstraint("CK_order_operations_incorporation_contents_price_non_negative", "applied_price >= 0");

                            t.HasCheckConstraint("CK_order_operations_incorporation_contents_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.Liquidation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("DeclaredPaymentMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("declared_payment_medium");

                    b.Property<decimal>("FunctionalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("functional_amount");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_liquidations");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_liquidations_order");

                    b.ToTable("liquidations", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_liquidations_amount_non_negative", "functional_amount >= 0");

                            t.HasCheckConstraint("CK_liquidations_medium_shape", "(mode = 'Simple' AND declared_payment_medium IS NOT NULL AND length(declared_payment_medium) BETWEEN 1 AND 200) OR (mode = 'ExternalCollection' AND declared_payment_medium IS NULL)");

                            t.HasCheckConstraint("CK_liquidations_mode", "mode IN ('Simple', 'ExternalCollection')");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.LiquidationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<string>("DeclaredPaymentMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("declared_payment_medium");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ResultDeclaredPaymentMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result_declared_payment_medium");

                    b.Property<decimal>("ResultFunctionalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("result_functional_amount");

                    b.Property<Guid>("ResultLiquidationId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_liquidation_id");

                    b.Property<string>("ResultMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_mode");

                    b.Property<DateTimeOffset>("ResultOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_occurred_at");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_order_operations_liquidation_commands");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_liquidation_commands_order");

                    b.HasIndex("ResultLiquidationId")
                        .IsUnique()
                        .HasDatabaseName("UX_liquidation_commands_liquidation");

                    b.ToTable("liquidation_commands", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_liquidation_commands_intent_medium", "(command_kind = 'LiquidateSimple' AND declared_payment_medium IS NOT NULL AND length(declared_payment_medium) BETWEEN 1 AND 200) OR (command_kind = 'RecordExternalCollection' AND declared_payment_medium IS NULL)");

                            t.HasCheckConstraint("CK_liquidation_commands_kind", "command_kind IN ('LiquidateSimple', 'RecordExternalCollection')");

                            t.HasCheckConstraint("CK_liquidation_commands_result_amount_non_negative", "result_functional_amount >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.LiquidationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("DeclaredPaymentMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("declared_payment_medium");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_kind");

                    b.Property<decimal>("FunctionalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("functional_amount");

                    b.Property<Guid>("LiquidationId")
                        .HasColumnType("uuid")
                        .HasColumnName("liquidation_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_liquidation_history");

                    b.HasIndex("LiquidationId")
                        .IsUnique()
                        .HasDatabaseName("UX_liquidation_history_liquidation");

                    b.HasIndex("OrderId", "OccurredAt", "Id")
                        .HasDatabaseName("IX_liquidation_history_order_time_id");

                    b.ToTable("liquidation_history", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_liquidation_history_amount_non_negative", "functional_amount >= 0");

                            t.HasCheckConstraint("CK_liquidation_history_event_kind", "event_kind = 'Liquidated'");

                            t.HasCheckConstraint("CK_liquidation_history_medium_shape", "(mode = 'Simple' AND declared_payment_medium IS NOT NULL AND length(declared_payment_medium) BETWEEN 1 AND 200) OR (mode = 'ExternalCollection' AND declared_payment_medium IS NULL)");

                            t.HasCheckConstraint("CK_liquidation_history_mode", "mode IN ('Simple', 'ExternalCollection')");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_orders");

                    b.ToTable("orders", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_orders_context_not_empty", "length(btrim(context)) > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PendingComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_identity_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_pending_compositions");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_pending_compositions_order");

                    b.ToTable("pending_compositions", "order_operations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PendingCompositionCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid?>("IntentPendingCompositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_pending_composition_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("ResultCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_created_at");

                    b.Property<Guid>("ResultCreatedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_created_by_identity_id");

                    b.Property<Guid>("ResultPendingCompositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_pending_composition_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_pending_composition_commands");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_pending_composition_commands_order");

                    b.ToTable("pending_composition_commands", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_pending_composition_commands_intent", "(command_kind = 'StartPendingComposition' AND intent_pending_composition_id IS NULL) OR (command_kind = 'DiscardPendingComposition' AND intent_pending_composition_id IS NOT NULL)");

                            t.HasCheckConstraint("CK_pending_composition_commands_kind", "command_kind IN ('StartPendingComposition', 'DiscardPendingComposition')");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ResultHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_history_id");

                    b.Property<int>("ResultInPreparationQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_in_preparation_quantity");

                    b.Property<DateTimeOffset>("ResultOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_occurred_at");

                    b.Property<int>("ResultPendingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_pending_quantity");

                    b.Property<int>("ResultReadyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_ready_quantity");

                    b.Property<int>("ResultTotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("result_total_quantity");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_order_operations_preparation_commands");

                    b.HasIndex("ResultHistoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_preparation_commands_history");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("IX_order_operations_preparation_commands_work");

                    b.ToTable("preparation_commands", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_preparation_commands_kind_not_empty", "length(btrim(command_kind)) > 0");

                            t.HasCheckConstraint("CK_preparation_commands_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_preparation_commands_result_balanced", "result_pending_quantity::bigint + result_in_preparation_quantity::bigint + result_ready_quantity::bigint = result_total_quantity::bigint");

                            t.HasCheckConstraint("CK_preparation_commands_result_non_negative", "result_pending_quantity >= 0 AND result_in_preparation_quantity >= 0 AND result_ready_quantity >= 0");

                            t.HasCheckConstraint("CK_preparation_commands_result_total_positive", "result_total_quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ResultingInPreparationQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_in_preparation_quantity");

                    b.Property<int>("ResultingPendingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_pending_quantity");

                    b.Property<int>("ResultingReadyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_ready_quantity");

                    b.Property<int>("ResultingTotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_total_quantity");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_preparation_history");

                    b.HasIndex("WorkId", "OccurredAt", "Id")
                        .HasDatabaseName("IX_order_operations_preparation_history_work_time_id");

                    b.ToTable("preparation_history", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_preparation_history_event_kind_not_empty", "length(btrim(event_kind)) > 0");

                            t.HasCheckConstraint("CK_preparation_history_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("CK_preparation_history_result_balanced", "resulting_pending_quantity::bigint + resulting_in_preparation_quantity::bigint + resulting_ready_quantity::bigint = resulting_total_quantity::bigint");

                            t.HasCheckConstraint("CK_preparation_history_result_non_negative", "resulting_pending_quantity >= 0 AND resulting_in_preparation_quantity >= 0 AND resulting_ready_quantity >= 0");

                            t.HasCheckConstraint("CK_preparation_history_result_total_positive", "resulting_total_quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContentOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("content_ordinal");

                    b.Property<int>("InPreparationQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("in_preparation_quantity");

                    b.Property<Guid>("IncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("incorporation_id");

                    b.Property<int>("PendingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("pending_quantity");

                    b.Property<Guid>("PreparationResponsibilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("preparation_responsibility_id");

                    b.Property<int>("ReadyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ready_quantity");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.HasKey("Id")
                        .HasName("PK_order_operations_preparation_work");

                    b.HasIndex("PreparationResponsibilityId")
                        .HasDatabaseName("IX_order_operations_preparation_work_responsibility");

                    b.HasIndex("IncorporationId", "ContentOrdinal")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_preparation_work_content");

                    b.ToTable("preparation_work", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_preparation_work_quantities_balanced", "pending_quantity::bigint + in_preparation_quantity::bigint + ready_quantity::bigint = total_quantity::bigint");

                            t.HasCheckConstraint("CK_order_operations_preparation_work_quantities_non_negative", "pending_quantity >= 0 AND in_preparation_quantity >= 0 AND ready_quantity >= 0");

                            t.HasCheckConstraint("CK_order_operations_preparation_work_total_positive", "total_quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<Guid>("IntentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_order_id");

                    b.Property<Guid?>("IntentPendingCompositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_pending_composition_id");

                    b.Property<Guid>("ResultIncorporationId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_incorporation_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_order_operations_subsequent_confirmation_commands");

                    b.HasIndex("IntentOrderId")
                        .HasDatabaseName("IX_order_operations_subsequent_confirmation_commands_intent_order");

                    b.HasIndex("ResultIncorporationId")
                        .IsUnique()
                        .HasDatabaseName("UX_order_operations_subsequent_confirmation_commands_result_incorporation");

                    b.ToTable("subsequent_confirmation_commands", "order_operations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommandContent", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("LineOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("line_ordinal");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IdempotencyKey", "LineOrdinal")
                        .HasName("PK_order_operations_subsequent_confirmation_command_contents");

                    b.ToTable("subsequent_confirmation_command_contents", "order_operations", t =>
                        {
                            t.HasCheckConstraint("CK_order_operations_subseq_command_contents_ordinal_positive", "line_ordinal > 0");

                            t.HasCheckConstraint("CK_order_operations_subsequent_confirmation_command_contents_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.OrderOperations.ConfirmationHistory", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Incorporation", null)
                        .WithMany()
                        .HasForeignKey("IncorporationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_confirmation_history_incorporations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.DeliveryHistory", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.DeliveryCommand", "ResultHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_delivery_commands_history");

                    b.HasOne("NexoBar.OrderOperations.IncorporationContent", null)
                        .WithMany()
                        .HasForeignKey("IncorporationId", "ContentOrdinal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_delivery_commands_content");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryHistory", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.IncorporationContent", null)
                        .WithMany()
                        .HasForeignKey("IncorporationId", "ContentOrdinal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_delivery_history_content");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.DeliveryState", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.IncorporationContent", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.DeliveryState", "IncorporationId", "ContentOrdinal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_delivery_states_content");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Incorporation", null)
                        .WithMany()
                        .HasForeignKey("ResultIncorporationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_first_confirmation_commands_incorporations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommandContent", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.FirstConfirmationCommand", null)
                        .WithMany()
                        .HasForeignKey("IdempotencyKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_first_confirmation_command_contents_commands");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.Incorporation", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_incorporations_orders");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.IncorporationContent", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Incorporation", null)
                        .WithMany()
                        .HasForeignKey("IncorporationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_incorporation_contents_incorporations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.Liquidation", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.Liquidation", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_liquidations_orders");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.LiquidationCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_liquidation_commands_orders");

                    b.HasOne("NexoBar.OrderOperations.Liquidation", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.LiquidationCommand", "ResultLiquidationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_liquidation_commands_liquidations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.LiquidationHistory", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Liquidation", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.LiquidationHistory", "LiquidationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_liquidation_history_liquidations");

                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_liquidation_history_orders");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PendingComposition", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_pending_compositions_orders");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PendingCompositionCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_pending_composition_commands_orders");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.PreparationHistory", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.PreparationCommand", "ResultHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_preparation_commands_history");

                    b.HasOne("NexoBar.OrderOperations.PreparationWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_preparation_commands_work");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationHistory", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.PreparationWork", null)
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_preparation_history_work");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.PreparationWork", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.IncorporationContent", null)
                        .WithOne()
                        .HasForeignKey("NexoBar.OrderOperations.PreparationWork", "IncorporationId", "ContentOrdinal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_preparation_work_content");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommand", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.Order", null)
                        .WithMany()
                        .HasForeignKey("IntentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_subsequent_confirmation_commands_orders");

                    b.HasOne("NexoBar.OrderOperations.Incorporation", null)
                        .WithMany()
                        .HasForeignKey("ResultIncorporationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_subsequent_confirmation_commands_incorporations");
                });

            modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommandContent", b =>
                {
                    b.HasOne("NexoBar.OrderOperations.SubsequentConfirmationCommand", null)
                        .WithMany()
                        .HasForeignKey("IdempotencyKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_order_operations_subsequent_confirmation_command_contents_commands");
                });
#pragma warning restore 612, 618
        }
    }
}
