// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.OrderOperations.Migrations;

[DbContext(typeof(OrderOperationsDbContext))]
[Migration("20260830210000_ReidentifyIncorporationContent")]
partial class ReidentifyIncorporationContent
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("order_operations")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexoBar.OrderOperations.Order", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("Context").IsRequired()
                .HasColumnType("text").HasColumnName("context");
            b.HasKey("Id").HasName("PK_order_operations_orders");
            b.ToTable("orders", "order_operations", t =>
                t.HasCheckConstraint(
                    "CK_order_operations_orders_context_not_empty",
                    "length(btrim(context)) > 0"));
        });

        modelBuilder.Entity("NexoBar.OrderOperations.Incorporation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
            b.Property<int>("Ordinal").HasColumnType("integer").HasColumnName("ordinal");
            b.HasKey("Id").HasName("PK_order_operations_incorporations");
            b.HasIndex("OrderId", "Ordinal").IsUnique()
                .HasDatabaseName("UX_order_operations_incorporations_order_ordinal");
            b.ToTable("incorporations", "order_operations", t =>
                t.HasCheckConstraint(
                    "CK_order_operations_incorporations_ordinal_positive",
                    "ordinal > 0"));
        });

        modelBuilder.Entity("NexoBar.OrderOperations.IncorporationContent", b =>
        {
            b.Property<Guid>("IncorporationId").HasColumnType("uuid")
                .HasColumnName("incorporation_id");
            b.Property<int>("ContentOrdinal").HasColumnType("integer")
                .HasColumnName("content_ordinal");
            b.Property<Guid>("ProductId").HasColumnType("uuid")
                .HasColumnName("product_id");
            b.Property<decimal>("AppliedPrice").HasColumnType("numeric")
                .HasColumnName("applied_price");
            b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
            b.HasKey("IncorporationId", "ContentOrdinal")
                .HasName("PK_order_operations_incorporation_contents");
            b.HasIndex("IncorporationId", "ProductId").IsUnique()
                .HasDatabaseName(
                    "UX_order_operations_incorporation_contents_product");
            b.ToTable("incorporation_contents", "order_operations", t =>
            {
                t.HasCheckConstraint(
                    "CK_order_operations_incorporation_contents_ordinal_positive",
                    "content_ordinal > 0");
                t.HasCheckConstraint(
                    "CK_order_operations_incorporation_contents_price_non_negative",
                    "applied_price >= 0");
                t.HasCheckConstraint(
                    "CK_order_operations_incorporation_contents_quantity_positive",
                    "quantity > 0");
            });
        });

        modelBuilder.Entity("NexoBar.OrderOperations.ConfirmationHistory", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("ConfirmedContext").IsRequired().HasColumnType("text")
                .HasColumnName("confirmed_context");
            b.Property<Guid>("IncorporationId").HasColumnType("uuid")
                .HasColumnName("incorporation_id");
            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
            b.HasKey("Id").HasName("PK_order_operations_confirmation_history");
            b.HasIndex("IncorporationId").IsUnique()
                .HasDatabaseName("UX_order_operations_confirmation_history_incorporation");
            b.ToTable("confirmation_history", "order_operations", t =>
                t.HasCheckConstraint(
                    "CK_order_operations_confirmation_history_context_not_empty",
                    "length(btrim(confirmed_context)) > 0"));
        });

        modelBuilder.Entity("NexoBar.OrderOperations.PreparationWork", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("IncorporationId").HasColumnType("uuid")
                .HasColumnName("incorporation_id");
            b.Property<int>("ContentOrdinal").HasColumnType("integer")
                .HasColumnName("content_ordinal");
            b.Property<int>("InPreparationQuantity").HasColumnType("integer")
                .HasColumnName("in_preparation_quantity");
            b.Property<int>("PendingQuantity").HasColumnType("integer")
                .HasColumnName("pending_quantity");
            b.Property<Guid>("PreparationResponsibilityId").HasColumnType("uuid")
                .HasColumnName("preparation_responsibility_id");
            b.Property<int>("ReadyQuantity").HasColumnType("integer")
                .HasColumnName("ready_quantity");
            b.Property<int>("TotalQuantity").HasColumnType("integer")
                .HasColumnName("total_quantity");
            b.HasKey("Id").HasName("PK_order_operations_preparation_work");
            b.HasIndex("PreparationResponsibilityId")
                .HasDatabaseName(
                    "IX_order_operations_preparation_work_responsibility");
            b.HasIndex("IncorporationId", "ContentOrdinal").IsUnique()
                .HasDatabaseName("UX_order_operations_preparation_work_content");
            b.ToTable("preparation_work", "order_operations", t =>
            {
                t.HasCheckConstraint(
                    "CK_order_operations_preparation_work_quantities_balanced",
                    "pending_quantity::bigint + in_preparation_quantity::bigint + " +
                    "ready_quantity::bigint = total_quantity::bigint");
                t.HasCheckConstraint(
                    "CK_order_operations_preparation_work_quantities_non_negative",
                    "pending_quantity >= 0 AND in_preparation_quantity >= 0 AND " +
                    "ready_quantity >= 0");
                t.HasCheckConstraint(
                    "CK_order_operations_preparation_work_total_positive",
                    "total_quantity > 0");
            });
        });

        modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommand", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid")
                .HasColumnName("idempotency_key");
            b.Property<string>("IntentContext").IsRequired().HasColumnType("text")
                .HasColumnName("intent_context");
            b.Property<Guid>("ResultIncorporationId").HasColumnType("uuid")
                .HasColumnName("result_incorporation_id");
            b.HasKey("IdempotencyKey")
                .HasName("PK_order_operations_first_confirmation_commands");
            b.HasIndex("ResultIncorporationId").IsUnique()
                .HasDatabaseName(
                    "UX_order_operations_first_confirmation_commands_result_incorporation");
            b.ToTable("first_confirmation_commands", "order_operations", t =>
                t.HasCheckConstraint(
                    "CK_order_operations_first_confirmation_commands_context_not_empty",
                    "length(btrim(intent_context)) > 0"));
        });

        modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommandContent", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid")
                .HasColumnName("idempotency_key");
            b.Property<int>("LineOrdinal").HasColumnType("integer")
                .HasColumnName("line_ordinal");
            b.Property<Guid>("ProductId").HasColumnType("uuid")
                .HasColumnName("product_id");
            b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
            b.HasKey("IdempotencyKey", "LineOrdinal")
                .HasName("PK_order_operations_first_confirmation_command_contents");
            b.HasIndex("IdempotencyKey", "ProductId").IsUnique()
                .HasDatabaseName(
                    "UX_order_operations_first_command_contents_product");
            b.ToTable("first_confirmation_command_contents", "order_operations", t =>
            {
                t.HasCheckConstraint(
                    "CK_order_operations_first_command_contents_ordinal_positive",
                    "line_ordinal > 0");
                t.HasCheckConstraint(
                    "CK_order_operations_first_confirmation_command_contents_quantity_positive",
                    "quantity > 0");
            });
        });

        modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommand", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid")
                .HasColumnName("idempotency_key");
            b.Property<Guid>("IntentOrderId").HasColumnType("uuid")
                .HasColumnName("intent_order_id");
            b.Property<Guid>("ResultIncorporationId").HasColumnType("uuid")
                .HasColumnName("result_incorporation_id");
            b.HasKey("IdempotencyKey")
                .HasName("PK_order_operations_subsequent_confirmation_commands");
            b.HasIndex("IntentOrderId")
                .HasDatabaseName(
                    "IX_order_operations_subsequent_confirmation_commands_intent_order");
            b.HasIndex("ResultIncorporationId").IsUnique()
                .HasDatabaseName(
                    "UX_order_operations_subsequent_confirmation_commands_result_incorporation");
            b.ToTable("subsequent_confirmation_commands", "order_operations");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommandContent", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid")
                .HasColumnName("idempotency_key");
            b.Property<int>("LineOrdinal").HasColumnType("integer")
                .HasColumnName("line_ordinal");
            b.Property<Guid>("ProductId").HasColumnType("uuid")
                .HasColumnName("product_id");
            b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
            b.HasKey("IdempotencyKey", "LineOrdinal")
                .HasName(
                    "PK_order_operations_subsequent_confirmation_command_contents");
            b.HasIndex("IdempotencyKey", "ProductId").IsUnique()
                .HasDatabaseName(
                    "UX_order_operations_subsequent_command_contents_product");
            b.ToTable("subsequent_confirmation_command_contents", "order_operations", t =>
            {
                t.HasCheckConstraint(
                    "CK_order_operations_subseq_command_contents_ordinal_positive",
                    "line_ordinal > 0");
                t.HasCheckConstraint(
                    "CK_order_operations_subsequent_confirmation_command_contents_quantity_positive",
                    "quantity > 0");
            });
        });

        modelBuilder.Entity("NexoBar.OrderOperations.Incorporation", b =>
        {
            b.HasOne("NexoBar.OrderOperations.Order", null).WithMany()
                .HasForeignKey("OrderId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName("FK_order_operations_incorporations_orders");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.IncorporationContent", b =>
        {
            b.HasOne("NexoBar.OrderOperations.Incorporation", null).WithMany()
                .HasForeignKey("IncorporationId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_incorporation_contents_incorporations");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.ConfirmationHistory", b =>
        {
            b.HasOne("NexoBar.OrderOperations.Incorporation", null).WithMany()
                .HasForeignKey("IncorporationId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_confirmation_history_incorporations");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommand", b =>
        {
            b.HasOne("NexoBar.OrderOperations.Incorporation", null).WithMany()
                .HasForeignKey("ResultIncorporationId")
                .OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_first_confirmation_commands_incorporations");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.FirstConfirmationCommandContent", b =>
        {
            b.HasOne("NexoBar.OrderOperations.FirstConfirmationCommand", null).WithMany()
                .HasForeignKey("IdempotencyKey").OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_first_confirmation_command_contents_commands");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommand", b =>
        {
            b.HasOne("NexoBar.OrderOperations.Order", null).WithMany()
                .HasForeignKey("IntentOrderId").OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_subsequent_confirmation_commands_orders");
            b.HasOne("NexoBar.OrderOperations.Incorporation", null).WithMany()
                .HasForeignKey("ResultIncorporationId")
                .OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_subsequent_confirmation_commands_incorporations");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.SubsequentConfirmationCommandContent", b =>
        {
            b.HasOne("NexoBar.OrderOperations.SubsequentConfirmationCommand", null)
                .WithMany().HasForeignKey("IdempotencyKey")
                .OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName(
                    "FK_order_operations_subsequent_confirmation_command_contents_commands");
        });

        modelBuilder.Entity("NexoBar.OrderOperations.PreparationWork", b =>
        {
            b.HasOne("NexoBar.OrderOperations.IncorporationContent", null).WithOne()
                .HasForeignKey("NexoBar.OrderOperations.PreparationWork", "IncorporationId", "ContentOrdinal")
                .OnDelete(DeleteBehavior.Restrict).IsRequired()
                .HasConstraintName("FK_order_operations_preparation_work_content");
        });
#pragma warning restore 612, 618
    }
}
