<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\NexoBar.Catalog\NexoBar.Catalog.csproj" />
    <ProjectReference Include="..\NexoBar.IdentitiesAndCapabilities\NexoBar.IdentitiesAndCapabilities.csproj" />
    <ProjectReference Include="..\NexoBar.Inventory\NexoBar.Inventory.csproj" />
    <ProjectReference Include="..\NexoBar.OperationalConfiguration\NexoBar.OperationalConfiguration.csproj" />
    <ProjectReference Include="..\NexoBar.OrderOperations\NexoBar.OrderOperations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\NexoBar.Host\appsettings*.json"
             Link="%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
