// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.IdentitiesAndCapabilities.Migrations;

[DbContext(typeof(IdentitiesAndCapabilitiesDbContext))]
[Migration("20260830234500_InitialIdentitiesAndCapabilities")]
partial class InitialIdentitiesAndCapabilities
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identities_and_capabilities")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");
            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");
            b.Property<string>("NormalizedOperationalName")
                .IsRequired()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("text")
                .HasColumnName("normalized_operational_name")
                .HasComputedColumnSql("lower(operational_name)", true);
            b.Property<string>("OperationalName")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("operational_name");
            b.HasKey("Id")
                .HasName("PK_identities_and_capabilities_identities");
            b.HasIndex("NormalizedOperationalName")
                .HasDatabaseName("IX_identity_normalized_operational_name");
            b.ToTable("identities", "identities_and_capabilities", t =>
                t.HasCheckConstraint(
                    "CK_identity_operational_name_trimmed_not_empty",
                    "operational_name = btrim(operational_name) AND " +
                    "length(operational_name) > 0"));
        });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<Guid>("PreparationResponsibilityId")
                    .HasColumnType("uuid")
                    .HasColumnName("preparation_responsibility_id");
                b.HasKey("IdentityId", "PreparationResponsibilityId")
                    .HasName("PK_preparation_enablements");
                b.ToTable(
                    "preparation_enablements",
                    "identities_and_capabilities");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<string>("ResponsibilityCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("responsibility_code");
                b.HasKey("IdentityId", "ResponsibilityCode")
                    .HasName("PK_responsibility_assignments");
                b.ToTable(
                    "responsibility_assignments",
                    "identities_and_capabilities",
                    t => t.HasCheckConstraint(
                        "CK_responsibility_assignment_code",
                        "responsibility_code IN (" +
                        "'OrderOperationsAndBasicClosure', " +
                        "'OperationalIntervention', " +
                        "'Preparation', " +
                        "'CatalogConfiguration', " +
                        "'InventoryOperation', " +
                        "'InventoryConfiguration', " +
                        "'GeneralConfiguration')"));
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("PreparationEnablements")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_preparation_enablements_identity");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("ResponsibilityAssignments")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_responsibility_assignments_identity");
            });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Navigation("PreparationEnablements");
            b.Navigation("ResponsibilityAssignments");
        });
#pragma warning restore 612, 618
    }
}
