// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.IdentitiesAndCapabilities.Migrations;

[DbContext(typeof(IdentitiesAndCapabilitiesDbContext))]
[Migration("20260831190000_AddIdentityAdministrationCommands")]
partial class AddIdentityAdministrationCommands
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identities_and_capabilities")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.IdentityAdministrativeCommand",
            b =>
            {
                b.Property<Guid>("IdempotencyKey")
                    .HasColumnType("uuid")
                    .HasColumnName("idempotency_key");
                b.Property<Guid>("ActorIdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("actor_identity_id");
                b.Property<string>("CommandKind")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("command_kind");
                b.Property<byte[]>("IntentFingerprint")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("intent_fingerprint");
                b.Property<string>("IntentSecretVerifier")
                    .HasColumnType("text")
                    .HasColumnName("intent_secret_verifier");
                b.Property<string>("ResultPayload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("result_payload");
                b.HasKey("IdempotencyKey")
                    .HasName("PK_administrative_commands");
                b.HasIndex("ActorIdentityId")
                    .HasDatabaseName(
                        "IX_administrative_commands_actor_identity_id");
                b.ToTable(
                    "administrative_commands",
                    "identities_and_capabilities",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_administrative_command_kind",
                            "command_kind IN (" +
                            "'CreateIdentity', " +
                            "'ChangeOperationalName', " +
                            "'ActivateIdentity', " +
                            "'DeactivateIdentity', " +
                            "'SetLocalCredential', " +
                            "'AssignResponsibility', " +
                            "'RevokeResponsibility', " +
                            "'GrantPreparationEnablement', " +
                            "'RevokePreparationEnablement')");
                        t.HasCheckConstraint(
                            "CK_administrative_command_secret_intent",
                            "(command_kind = 'SetLocalCredential' AND " +
                            "intent_secret_verifier IS NOT NULL) OR " +
                            "(command_kind <> 'SetLocalCredential' AND " +
                            "intent_secret_verifier IS NULL)");
                    });
            });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");
            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");
            b.Property<string>("NormalizedOperationalName")
                .IsRequired()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("text")
                .HasColumnName("normalized_operational_name")
                .HasComputedColumnSql("lower(operational_name)", true);
            b.Property<string>("OperationalName")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("operational_name");
            b.HasKey("Id")
                .HasName("PK_identities_and_capabilities_identities");
            b.HasIndex("NormalizedOperationalName")
                .HasDatabaseName("IX_identity_normalized_operational_name");
            b.ToTable("identities", "identities_and_capabilities", t =>
                t.HasCheckConstraint(
                    "CK_identity_operational_name_trimmed_not_empty",
                    "operational_name = btrim(operational_name) AND " +
                    "length(operational_name) > 0"));
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.IdentitySession", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");
            b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("absolute_expires_at");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            b.Property<Guid>("IdentityId")
                .HasColumnType("uuid")
                .HasColumnName("identity_id");
            b.Property<DateTimeOffset>("LastActivityAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_activity_at");
            b.Property<DateTimeOffset?>("RevokedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("revoked_at");
            b.Property<byte[]>("TokenHash")
                .IsRequired()
                .HasColumnType("bytea")
                .HasColumnName("token_hash");
            b.HasKey("Id")
                .HasName("PK_sessions");
            b.HasIndex("IdentityId")
                .HasDatabaseName("IX_session_identity_id");
            b.HasIndex("TokenHash")
                .IsUnique()
                .HasDatabaseName("UX_session_token_hash");
            b.ToTable("sessions", "identities_and_capabilities", t =>
            {
                t.HasCheckConstraint(
                    "CK_session_absolute_expiration",
                    "absolute_expires_at > created_at");
                t.HasCheckConstraint(
                    "CK_session_last_activity",
                    "last_activity_at >= created_at AND " +
                    "last_activity_at < absolute_expires_at");
                t.HasCheckConstraint(
                    "CK_session_revoked_at",
                    "revoked_at IS NULL OR revoked_at >= created_at");
            });
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.LocalCredential", b =>
        {
            b.Property<Guid>("IdentityId")
                .HasColumnType("uuid")
                .HasColumnName("identity_id");
            b.Property<string>("LoginIdentifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("login_identifier");
            b.Property<string>("NormalizedLoginIdentifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("normalized_login_identifier");
            b.Property<string>("SecretVerifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("secret_verifier");
            b.HasKey("IdentityId")
                .HasName("PK_local_credentials");
            b.HasIndex("NormalizedLoginIdentifier")
                .IsUnique()
                .HasDatabaseName("UX_local_credential_normalized_login");
            b.ToTable("local_credentials", "identities_and_capabilities", t =>
            {
                t.HasCheckConstraint(
                    "CK_local_credential_login_identifier",
                    "login_identifier = btrim(login_identifier) AND " +
                    "length(login_identifier) > 0");
                t.HasCheckConstraint(
                    "CK_local_credential_normalized_login",
                    "normalized_login_identifier = " +
                    "btrim(normalized_login_identifier) AND " +
                    "length(normalized_login_identifier) > 0");
                t.HasCheckConstraint(
                    "CK_local_credential_secret_verifier",
                    "length(secret_verifier) > 0");
            });
        });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<Guid>("PreparationResponsibilityId")
                    .HasColumnType("uuid")
                    .HasColumnName("preparation_responsibility_id");
                b.HasKey("IdentityId", "PreparationResponsibilityId")
                    .HasName("PK_preparation_enablements");
                b.ToTable(
                    "preparation_enablements",
                    "identities_and_capabilities");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.IdentityAdministrativeCommand",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany()
                    .HasForeignKey("ActorIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_administrative_command_actor");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<string>("ResponsibilityCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("responsibility_code");
                b.HasKey("IdentityId", "ResponsibilityCode")
                    .HasName("PK_responsibility_assignments");
                b.ToTable(
                    "responsibility_assignments",
                    "identities_and_capabilities",
                    t => t.HasCheckConstraint(
                        "CK_responsibility_assignment_code",
                        "responsibility_code IN (" +
                        "'OrderOperationsAndBasicClosure', " +
                        "'OperationalIntervention', " +
                        "'Preparation', " +
                        "'CatalogConfiguration', " +
                        "'InventoryOperation', " +
                        "'InventoryConfiguration', " +
                        "'GeneralConfiguration')"));
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("PreparationEnablements")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_preparation_enablements_identity");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("ResponsibilityAssignments")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_responsibility_assignments_identity");
            });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Navigation("PreparationEnablements");
            b.Navigation("ResponsibilityAssignments");
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.IdentitySession", b =>
        {
            b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                .WithMany()
                .HasForeignKey("IdentityId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("FK_session_identity");
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.LocalCredential", b =>
        {
            b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                .WithOne()
                .HasForeignKey("NexoBar.IdentitiesAndCapabilities.LocalCredential", "IdentityId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("FK_local_credential_identity");
        });
#pragma warning restore 612, 618
    }
}
