// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.IdentitiesAndCapabilities.Migrations;

[DbContext(typeof(IdentitiesAndCapabilitiesDbContext))]
partial class IdentitiesAndCapabilitiesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identities_and_capabilities")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.InstallationProvisioningFact",
            b =>
            {
                b.Property<short>("Key")
                    .HasColumnType("smallint")
                    .HasColumnName("singleton_key");
                b.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("completed_at");
                b.Property<Guid?>("InitialIdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("initial_identity_id");
                b.Property<string>("Origin")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("origin");
                b.Property<Guid?>("ProvisioningCommandId")
                    .HasColumnType("uuid")
                    .HasColumnName("provisioning_command_id");
                b.Property<byte[]>("RetryIntentFingerprint")
                    .HasColumnType("bytea")
                    .HasColumnName("retry_intent_fingerprint");
                b.Property<string>("RetryRecoveryFactorVerifier")
                    .HasColumnType("text")
                    .HasColumnName("retry_recovery_factor_verifier");
                b.Property<string>("RetrySecretVerifier")
                    .HasColumnType("text")
                    .HasColumnName("retry_secret_verifier");
                b.HasKey("Key")
                    .HasName("PK_installation_provisioning");
                b.ToTable(
                    "installation_provisioning",
                    "identities_and_capabilities",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_installation_provisioning_singleton",
                            "singleton_key = 1");
                        t.HasCheckConstraint(
                            "CK_installation_provisioning_origin",
                            "origin IN ('InitialProvisioning', 'LegacyBackfill')");
                        t.HasCheckConstraint(
                            "CK_installation_provisioning_initial_fields",
                            "(origin = 'InitialProvisioning' AND " +
                            "completed_at IS NOT NULL AND " +
                            "provisioning_command_id IS NOT NULL AND " +
                            "initial_identity_id IS NOT NULL AND " +
                            "retry_intent_fingerprint IS NOT NULL AND " +
                            "octet_length(retry_intent_fingerprint) > 0 AND " +
                            "retry_secret_verifier IS NOT NULL AND " +
                            "length(retry_secret_verifier) > 0) OR " +
                            "(origin = 'LegacyBackfill' AND " +
                            "completed_at IS NULL AND " +
                            "provisioning_command_id IS NULL AND " +
                            "initial_identity_id IS NULL AND " +
                            "retry_intent_fingerprint IS NULL AND " +
                            "retry_secret_verifier IS NULL)");
                    });
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ExtraordinaryGeneralConfigurationRecoveryCommand",
            b =>
            {
                b.Property<Guid>("CommandId")
                    .HasColumnType("uuid")
                    .HasColumnName("command_id");
                b.Property<DateTimeOffset>("CompletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("completed_at");
                b.Property<string>("LoginIntentMode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("login_intent_mode");
                b.Property<int>("RecoveryFactorGeneration")
                    .HasColumnType("integer")
                    .HasColumnName("recovery_factor_generation");
                b.Property<string>("RequestedLoginIdentifier")
                    .HasColumnType("text")
                    .HasColumnName("requested_login_identifier");
                b.Property<string>("RetryCredentialVerifier")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("retry_credential_verifier");
                b.Property<Guid>("TargetIdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_identity_id");
                b.HasKey("CommandId")
                    .HasName("PK_extraordinary_general_configuration_recovery_commands");
                b.HasIndex("TargetIdentityId")
                    .HasDatabaseName(
                        "IX_extraordinary_recovery_commands_target_identity_id");
                b.ToTable(
                    "extraordinary_general_configuration_recovery_commands",
                    "identities_and_capabilities",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_extraordinary_recovery_command_login_intent",
                            "login_intent_mode IN ('PreserveExisting', 'ExplicitIdentifier')");
                        t.HasCheckConstraint(
                            "CK_extraordinary_recovery_command_requested_login",
                            "(login_intent_mode = 'PreserveExisting' AND " +
                            "requested_login_identifier IS NULL) OR " +
                            "(login_intent_mode = 'ExplicitIdentifier' AND " +
                            "requested_login_identifier IS NOT NULL AND " +
                            "length(requested_login_identifier) > 0)");
                        t.HasCheckConstraint(
                            "CK_extraordinary_recovery_command_generation",
                            "recovery_factor_generation > 0");
                        t.HasCheckConstraint(
                            "CK_extraordinary_recovery_command_credential_verifier",
                            "length(retry_credential_verifier) > 0");
                    });
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.InstallationRecoveryState",
            b =>
            {
                b.Property<short>("Key")
                    .HasColumnType("smallint")
                    .HasColumnName("singleton_key");
                b.Property<DateTimeOffset>("EstablishedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("established_at");
                b.Property<int>("Generation")
                    .HasColumnType("integer")
                    .HasColumnName("generation");
                b.Property<DateTimeOffset?>("LastRotatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_rotated_at");
                b.Property<string>("RecoveryFactorVerifier")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("recovery_factor_verifier");
                b.HasKey("Key")
                    .HasName("PK_installation_recovery_state");
                b.ToTable(
                    "installation_recovery_state",
                    "identities_and_capabilities",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_installation_recovery_state_singleton",
                            "singleton_key = 1");
                        t.HasCheckConstraint(
                            "CK_installation_recovery_state_generation",
                            "generation > 0");
                        t.HasCheckConstraint(
                            "CK_installation_recovery_state_rotation_time",
                            "last_rotated_at IS NULL OR last_rotated_at >= established_at");
                        t.HasCheckConstraint(
                            "CK_installation_recovery_state_verifier",
                            "length(recovery_factor_verifier) > 0");
                    });
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.IdentityAdministrativeCommand",
            b =>
            {
                b.Property<Guid>("IdempotencyKey")
                    .HasColumnType("uuid")
                    .HasColumnName("idempotency_key");
                b.Property<Guid>("ActorIdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("actor_identity_id");
                b.Property<string>("CommandKind")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("command_kind");
                b.Property<byte[]>("IntentFingerprint")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("intent_fingerprint");
                b.Property<string>("IntentSecretVerifier")
                    .HasColumnType("text")
                    .HasColumnName("intent_secret_verifier");
                b.Property<string>("ResultPayload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("result_payload");
                b.HasKey("IdempotencyKey")
                    .HasName("PK_administrative_commands");
                b.HasIndex("ActorIdentityId")
                    .HasDatabaseName(
                        "IX_administrative_commands_actor_identity_id");
                b.ToTable(
                    "administrative_commands",
                    "identities_and_capabilities",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_administrative_command_kind",
                            "command_kind IN (" +
                            "'CreateIdentity', " +
                            "'ChangeOperationalName', " +
                            "'ActivateIdentity', " +
                            "'DeactivateIdentity', " +
                            "'SetLocalCredential', " +
                            "'AssignResponsibility', " +
                            "'RevokeResponsibility', " +
                            "'GrantPreparationEnablement', " +
                            "'RevokePreparationEnablement', " +
                            "'RotateInstallationRecoveryFactor')");
                        t.HasCheckConstraint(
                            "CK_administrative_command_secret_intent",
                            "(command_kind IN ('SetLocalCredential', " +
                            "'RotateInstallationRecoveryFactor') AND " +
                            "intent_secret_verifier IS NOT NULL) OR " +
                            "(command_kind NOT IN ('SetLocalCredential', " +
                            "'RotateInstallationRecoveryFactor') AND " +
                            "intent_secret_verifier IS NULL)");
                    });
            });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");
            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");
            b.Property<string>("NormalizedOperationalName")
                .IsRequired()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("text")
                .HasColumnName("normalized_operational_name")
                .HasComputedColumnSql("lower(operational_name)", true);
            b.Property<string>("OperationalName")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("operational_name");
            b.HasKey("Id")
                .HasName("PK_identities_and_capabilities_identities");
            b.HasIndex("NormalizedOperationalName")
                .HasDatabaseName("IX_identity_normalized_operational_name");
            b.ToTable("identities", "identities_and_capabilities", t =>
                t.HasCheckConstraint(
                    "CK_identity_operational_name_trimmed_not_empty",
                    "operational_name = btrim(operational_name) AND " +
                    "length(operational_name) > 0"));
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.IdentitySession", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");
            b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("absolute_expires_at");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");
            b.Property<Guid>("IdentityId")
                .HasColumnType("uuid")
                .HasColumnName("identity_id");
            b.Property<DateTimeOffset>("LastActivityAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_activity_at");
            b.Property<DateTimeOffset?>("RevokedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("revoked_at");
            b.Property<byte[]>("TokenHash")
                .IsRequired()
                .HasColumnType("bytea")
                .HasColumnName("token_hash");
            b.HasKey("Id")
                .HasName("PK_sessions");
            b.HasIndex("IdentityId")
                .HasDatabaseName("IX_session_identity_id");
            b.HasIndex("TokenHash")
                .IsUnique()
                .HasDatabaseName("UX_session_token_hash");
            b.ToTable("sessions", "identities_and_capabilities", t =>
            {
                t.HasCheckConstraint(
                    "CK_session_absolute_expiration",
                    "absolute_expires_at > created_at");
                t.HasCheckConstraint(
                    "CK_session_last_activity",
                    "last_activity_at >= created_at AND " +
                    "last_activity_at < absolute_expires_at");
                t.HasCheckConstraint(
                    "CK_session_revoked_at",
                    "revoked_at IS NULL OR revoked_at >= created_at");
            });
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.LocalCredential", b =>
        {
            b.Property<Guid>("IdentityId")
                .HasColumnType("uuid")
                .HasColumnName("identity_id");
            b.Property<string>("LoginIdentifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("login_identifier");
            b.Property<string>("NormalizedLoginIdentifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("normalized_login_identifier");
            b.Property<string>("SecretVerifier")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("secret_verifier");
            b.HasKey("IdentityId")
                .HasName("PK_local_credentials");
            b.HasIndex("NormalizedLoginIdentifier")
                .IsUnique()
                .HasDatabaseName("UX_local_credential_normalized_login");
            b.ToTable("local_credentials", "identities_and_capabilities", t =>
            {
                t.HasCheckConstraint(
                    "CK_local_credential_login_identifier",
                    "login_identifier = btrim(login_identifier) AND " +
                    "length(login_identifier) > 0");
                t.HasCheckConstraint(
                    "CK_local_credential_normalized_login",
                    "normalized_login_identifier = " +
                    "btrim(normalized_login_identifier) AND " +
                    "length(normalized_login_identifier) > 0");
                t.HasCheckConstraint(
                    "CK_local_credential_secret_verifier",
                    "length(secret_verifier) > 0");
            });
        });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<Guid>("PreparationResponsibilityId")
                    .HasColumnType("uuid")
                    .HasColumnName("preparation_responsibility_id");
                b.HasKey("IdentityId", "PreparationResponsibilityId")
                    .HasName("PK_preparation_enablements");
                b.ToTable(
                    "preparation_enablements",
                    "identities_and_capabilities");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.IdentityAdministrativeCommand",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany()
                    .HasForeignKey("ActorIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_administrative_command_actor");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.Property<Guid>("IdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("identity_id");
                b.Property<string>("ResponsibilityCode")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("responsibility_code");
                b.HasKey("IdentityId", "ResponsibilityCode")
                    .HasName("PK_responsibility_assignments");
                b.ToTable(
                    "responsibility_assignments",
                    "identities_and_capabilities",
                    t => t.HasCheckConstraint(
                        "CK_responsibility_assignment_code",
                        "responsibility_code IN (" +
                        "'OrderOperationsAndBasicClosure', " +
                        "'OperationalIntervention', " +
                        "'Preparation', " +
                        "'CatalogConfiguration', " +
                        "'InventoryOperation', " +
                        "'InventoryConfiguration', " +
                        "'GeneralConfiguration')"));
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.PreparationEnablement",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("PreparationEnablements")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_preparation_enablements_identity");
            });

        modelBuilder.Entity(
            "NexoBar.IdentitiesAndCapabilities.ResponsibilityAssignment",
            b =>
            {
                b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                    .WithMany("ResponsibilityAssignments")
                    .HasForeignKey("IdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_responsibility_assignments_identity");
            });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.Identity", b =>
        {
            b.Navigation("PreparationEnablements");
            b.Navigation("ResponsibilityAssignments");
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.IdentitySession", b =>
        {
            b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                .WithMany()
                .HasForeignKey("IdentityId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("FK_session_identity");
        });

        modelBuilder.Entity("NexoBar.IdentitiesAndCapabilities.LocalCredential", b =>
        {
            b.HasOne("NexoBar.IdentitiesAndCapabilities.Identity", null)
                .WithOne()
                .HasForeignKey("NexoBar.IdentitiesAndCapabilities.LocalCredential", "IdentityId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("FK_local_credential_identity");
        });
#pragma warning restore 612, 618
    }
}
