// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoBar.Catalog;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260828180254_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoBar.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("NormalizedOperationalName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_operational_name")
                        .HasComputedColumnSql("lower(operational_name)", true);

                    b.Property<string>("OperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operational_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<bool>("RequiresPreparation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_preparation");

                    b.HasKey("Id")
                        .HasName("PK_catalog_products");

                    b.HasIndex("NormalizedOperationalName")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_products_active_normalized_operational_name")
                        .HasFilter("is_active");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_products_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("CK_catalog_products_requires_preparation_i1", "requires_preparation = false");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductCreationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("IntentOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_operational_name");

                    b.Property<decimal>("IntentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("intent_price");

                    b.Property<bool>("IntentRequiresPreparation")
                        .HasColumnType("boolean")
                        .HasColumnName("intent_requires_preparation");

                    b.Property<bool>("ResultIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_active");

                    b.Property<bool>("ResultIsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_available");

                    b.Property<Guid>("ResultProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_product_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_creation_commands");

                    b.HasIndex("ResultProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_product_creation_commands_result_product_id");

                    b.ToTable("product_creation_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_creation_commands_i1_result", "intent_requires_preparation = false AND result_is_active = true AND result_is_available = true");

                            t.HasCheckConstraint("CK_catalog_product_creation_commands_price_non_negative", "intent_price >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductCreationCommand", b =>
                {
                    b.HasOne("NexoBar.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ResultProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_catalog_product_creation_commands_products");
                });
#pragma warning restore 612, 618
        }
    }
}
