// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoBar.Catalog;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoBar.Catalog.CatalogGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedOperationalName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_operational_name")
                        .HasComputedColumnSql("lower(operational_name)", true);

                    b.Property<string>("OperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operational_name");

                    b.HasKey("Id")
                        .HasName("PK_catalog_groups");

                    b.HasIndex("NormalizedOperationalName")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_groups_normalized_operational_name");

                    b.ToTable("groups", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_groups_operational_name_not_blank", "length(btrim(operational_name)) > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.GroupCreationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<string>("IntentOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_operational_name");

                    b.Property<Guid>("ResultGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_group_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_group_creation_commands");

                    b.HasIndex("ResultGroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_group_creation_commands_result_group_id");

                    b.ToTable("group_creation_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_group_creation_commands_intent_name_not_blank", "length(btrim(intent_operational_name)) > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("NormalizedOperationalName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_operational_name")
                        .HasComputedColumnSql("lower(operational_name)", true);

                    b.Property<string>("OperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operational_name");

                    b.Property<Guid?>("PreparationResponsibilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("preparation_responsibility_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<bool>("RequiresPreparation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_preparation");

                    b.HasKey("Id")
                        .HasName("PK_catalog_products");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedOperationalName")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_products_active_normalized_operational_name")
                        .HasFilter("is_active");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_products_preparation_configuration_coherent", "(requires_preparation = false AND preparation_responsibility_id IS NULL) OR (requires_preparation = true AND preparation_responsibility_id IS NOT NULL)");

                            t.HasCheckConstraint("CK_catalog_products_price_non_negative", "price >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductCreationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<string>("IntentOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_operational_name");

                    b.Property<decimal>("IntentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("intent_price");

                    b.Property<bool>("IntentRequiresPreparation")
                        .HasColumnType("boolean")
                        .HasColumnName("intent_requires_preparation");

                    b.Property<bool>("ResultIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_active");

                    b.Property<bool>("ResultIsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_available");

                    b.Property<Guid>("ResultProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_product_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_creation_commands");

                    b.HasIndex("ResultProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_catalog_product_creation_commands_result_product_id");

                    b.ToTable("product_creation_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_creation_commands_i1_result", "intent_requires_preparation = false AND result_is_active = true AND result_is_available = true");

                            t.HasCheckConstraint("CK_catalog_product_creation_commands_price_non_negative", "intent_price >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductGroupChangeCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid?>("IntentExpectedGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_expected_group_id");

                    b.Property<Guid?>("IntentNewGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_new_group_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ResultGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_group_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_group_change_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_group_change_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_group_change_commands_result_matches_intent", "result_group_id IS NOT DISTINCT FROM intent_new_group_id");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductOperationalNameChangeCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<string>("IntentExpectedOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_expected_operational_name");

                    b.Property<string>("IntentNewOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_new_operational_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ResultOperationalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_operational_name");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_operational_name_change_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_operational_name_change_commands", "catalog");
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductPreparationConfigurationChangeCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid?>("IntentExpectedResponsibilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_expected_responsibility_id");

                    b.Property<Guid?>("IntentNewResponsibilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_new_responsibility_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ResultResponsibilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_responsibility_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_preparation_configuration_change_commands");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_catalog_product_prep_config_cmd_product");

                    b.ToTable("product_preparation_configuration_change_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_prep_config_cmd_result_matches_intent", "result_responsibility_id IS NOT DISTINCT FROM intent_new_responsibility_id");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductPriceChangeCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<decimal>("IntentExpectedCurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("intent_expected_current_price");

                    b.Property<decimal>("IntentNewPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("intent_new_price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("ResultPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("result_price");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_price_change_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_price_change_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_price_change_commands_intent_new_price_non_negative", "intent_new_price >= 0");

                            t.HasCheckConstraint("CK_catalog_product_price_change_commands_result_matches_intent", "result_price = intent_new_price");

                            t.HasCheckConstraint("CK_catalog_product_price_change_commands_result_price_non_negative", "result_price >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductReactivateCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("ResultIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_active");

                    b.Property<bool>("ResultIsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_available");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_reactivate_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_reactivate_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_reactivate_commands_result", "result_is_active = true AND result_is_available = true");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductRetireCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("ResultIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_active");

                    b.Property<bool>("ResultIsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("result_is_available");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_retire_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_retire_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_retire_commands_result", "result_is_active = false");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductDeleteCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_delete_commands");

                    b.ToTable("product_delete_commands", "catalog");
                });

            modelBuilder.Entity("NexoBar.Catalog.ProductAvailabilityChangeCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_kind");

                    b.Property<bool>("IntentExpectedCurrentAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("intent_expected_current_availability");

                    b.Property<bool>("IntentNewAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("intent_new_availability");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("ResultAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("result_availability");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_catalog_product_availability_change_commands");

                    b.HasIndex("ProductId");

                    b.ToTable("product_availability_change_commands", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_product_availability_change_commands_result_matches_intent", "result_availability = intent_new_availability");
                        });
                });

            modelBuilder.Entity("NexoBar.Catalog.GroupCreationCommand", b =>
                {
                    b.HasOne("NexoBar.Catalog.CatalogGroup", null)
                        .WithMany()
                        .HasForeignKey("ResultGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_catalog_group_creation_commands_groups");
                });

            modelBuilder.Entity("NexoBar.Catalog.Product", b =>
                {
                    b.HasOne("NexoBar.Catalog.CatalogGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_catalog_products_groups");
                });

#pragma warning restore 612, 618
        }
    }
}
