// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.OperationalConfiguration.Migrations;

[DbContext(typeof(OperationalConfigurationDbContext))]
[Migration("20260830120000_InitialOperationalConfiguration")]
partial class InitialOperationalConfiguration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("operational_configuration")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.PreparationResponsibility",
            b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");
                b.Property<string>("NormalizedOperationalName")
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("text")
                    .HasColumnName("normalized_operational_name")
                    .HasComputedColumnSql("lower(operational_name)", true);
                b.Property<string>("OperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("operational_name");
                b.HasKey("Id")
                    .HasName(
                        "PK_operational_configuration_preparation_responsibilities");
                b.HasIndex("NormalizedOperationalName")
                    .IsUnique()
                    .HasDatabaseName(
                        "UX_operational_configuration_responsibilities_normalized_name");
                b.ToTable(
                    "preparation_responsibilities",
                    "operational_configuration",
                    t => t.HasCheckConstraint(
                        "CK_op_config_preparation_responsibilities_name_not_empty",
                        "length(btrim(operational_name)) > 0"));
            });

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.PreparationResponsibilityCreationCommand",
            b =>
            {
                b.Property<Guid>("IdempotencyKey")
                    .HasColumnType("uuid")
                    .HasColumnName("idempotency_key");
                b.Property<string>("IntentOperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("intent_operational_name");
                b.Property<string>("ResultOperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("result_operational_name");
                b.Property<Guid>("ResultResponsibilityId")
                    .HasColumnType("uuid")
                    .HasColumnName("result_responsibility_id");
                b.HasKey("IdempotencyKey")
                    .HasName(
                        "PK_op_config_preparation_responsibility_creation_commands");
                b.HasIndex("ResultResponsibilityId")
                    .IsUnique()
                    .HasDatabaseName(
                        "UX_op_config_preparation_responsibility_creation_cmd_result");
                b.ToTable(
                    "preparation_responsibility_creation_commands",
                    "operational_configuration",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_operational_configuration_responsibility_cmd_intent_name",
                            "length(btrim(intent_operational_name)) > 0");
                        t.HasCheckConstraint(
                            "CK_operational_configuration_responsibility_cmd_result_name",
                            "length(btrim(result_operational_name)) > 0");
                    });
            });

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.PreparationResponsibilityCreationCommand",
            b =>
            {
                b.HasOne(
                        "NexoBar.OperationalConfiguration.PreparationResponsibility",
                        null)
                    .WithMany()
                    .HasForeignKey("ResultResponsibilityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName(
                        "FK_op_config_prep_responsibility_creation_cmd_responsibility");
            });
#pragma warning restore 612, 618
    }
}
