// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.OperationalConfiguration.Migrations;


partial class AddConfigurationLifecycle
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("operational_configuration")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.OperationalContext",
            b =>
            {
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasColumnName("is_active").HasDefaultValue(true);
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("NormalizedOperationalName").IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("text").HasColumnName("normalized_operational_name").HasComputedColumnSql("lower(operational_name)", true);
                b.Property<string>("OperationalName").IsRequired().HasColumnType("text").HasColumnName("operational_name");
                b.HasKey("Id").HasName("PK_operational_configuration_contexts");
                b.HasIndex("NormalizedOperationalName").IsUnique().HasDatabaseName("UX_operational_configuration_contexts_normalized_name");
                b.ToTable("contexts", "operational_configuration", t => t.HasCheckConstraint("CK_operational_configuration_contexts_name_not_empty", "length(btrim(operational_name)) > 0"));
            });

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.OperationalContextCreationCommand",
            b =>
            {
                b.Property<Guid>("IdempotencyKey").HasColumnType("uuid").HasColumnName("idempotency_key");
                b.Property<Guid>("ActorIdentityId").HasColumnType("uuid").HasColumnName("actor_identity_id");
                b.Property<string>("IntentOperationalName").IsRequired().HasColumnType("text").HasColumnName("intent_operational_name");
                b.Property<Guid>("ResultContextId").HasColumnType("uuid").HasColumnName("result_context_id");
                b.Property<string>("ResultOperationalName").IsRequired().HasColumnType("text").HasColumnName("result_operational_name");
                b.HasKey("IdempotencyKey").HasName("PK_operational_configuration_context_creation_commands");
                b.HasIndex("ResultContextId").IsUnique().HasDatabaseName("UX_op_config_context_creation_command_result");
                b.ToTable("context_creation_commands", "operational_configuration", t => t.HasCheckConstraint("CK_operational_configuration_context_creation_command_names_not_empty", "length(btrim(intent_operational_name)) > 0 AND length(btrim(result_operational_name)) > 0"));
            });


        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.PreparationResponsibility",
            b =>
            {
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasColumnName("is_active").HasDefaultValue(true);
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");
                b.Property<string>("NormalizedOperationalName")
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("text")
                    .HasColumnName("normalized_operational_name")
                    .HasComputedColumnSql("lower(operational_name)", true);
                b.Property<string>("OperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("operational_name");
                b.HasKey("Id")
                    .HasName(
                        "PK_operational_configuration_preparation_responsibilities");
                b.HasIndex("NormalizedOperationalName")
                    .IsUnique()
                    .HasDatabaseName(
                        "UX_operational_configuration_responsibilities_normalized_name");
                b.ToTable(
                    "preparation_responsibilities",
                    "operational_configuration",
                    t => t.HasCheckConstraint(
                        "CK_op_config_preparation_responsibilities_name_not_empty",
                        "length(btrim(operational_name)) > 0"));
            });

        modelBuilder.Entity(
            "NexoBar.OperationalConfiguration.PreparationResponsibilityCreationCommand",
            b =>
            {
                b.Property<Guid>("IdempotencyKey")
                    .HasColumnType("uuid")
                    .HasColumnName("idempotency_key");
                b.Property<Guid?>("ActorIdentityId")
                    .HasColumnType("uuid")
                    .HasColumnName("actor_identity_id");
                b.Property<string>("CommandKind")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("command_kind");
                b.Property<string>("IntentOperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("intent_operational_name");
                b.Property<string>("ResultOperationalName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("result_operational_name");
                b.Property<Guid>("ResultResponsibilityId")
                    .HasColumnType("uuid")
                    .HasColumnName("result_responsibility_id");
                b.HasKey("IdempotencyKey")
                    .HasName(
                        "PK_op_config_preparation_responsibility_creation_commands");
                b.HasIndex("ResultResponsibilityId")
                    .IsUnique()
                    .HasDatabaseName(
                        "UX_op_config_preparation_responsibility_creation_cmd_result");
                b.ToTable(
                    "preparation_responsibility_creation_commands",
                    "operational_configuration",
                    t =>
                    {
                        t.HasCheckConstraint(
                            "CK_operational_configuration_responsibility_cmd_intent_name",
                            "length(btrim(intent_operational_name)) > 0");
                        t.HasCheckConstraint(
                            "CK_operational_configuration_responsibility_cmd_result_name",
                            "length(btrim(result_operational_name)) > 0");
                    });
            });

        modelBuilder.Entity("NexoBar.OperationalConfiguration.OperationalContextLifecycleCommand", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid").HasColumnName("idempotency_key");
            b.Property<Guid>("ActorIdentityId").HasColumnType("uuid").HasColumnName("actor_identity_id");
            b.Property<string>("CommandKind").IsRequired().HasColumnType("text").HasColumnName("command_kind");
            b.Property<Guid>("TargetId").HasColumnType("uuid").HasColumnName("target_id");
            b.Property<string>("ExpectedOperationalName").IsRequired().HasColumnType("text").HasColumnName("expected_operational_name");
            b.Property<bool>("ExpectedIsActive").HasColumnType("boolean").HasColumnName("expected_is_active");
            b.Property<string>("NewOperationalName").HasColumnType("text").HasColumnName("new_operational_name");
            b.Property<string>("ResultOperationalName").IsRequired().HasColumnType("text").HasColumnName("result_operational_name");
            b.Property<bool>("ResultIsActive").HasColumnType("boolean").HasColumnName("result_is_active");
            b.Property<bool>("ResultIsDeleted").HasColumnType("boolean").HasColumnName("result_is_deleted");
            b.HasKey("IdempotencyKey");
            b.ToTable("context_lifecycle_commands", "operational_configuration", t => t.HasCheckConstraint("CK_context_lifecycle_commands_kind", "command_kind IN ('Rename', 'Retire', 'Reactivate', 'Delete')"));
        });
        modelBuilder.Entity("NexoBar.OperationalConfiguration.PreparationResponsibilityLifecycleCommand", b =>
        {
            b.Property<Guid>("IdempotencyKey").HasColumnType("uuid").HasColumnName("idempotency_key");
            b.Property<Guid>("ActorIdentityId").HasColumnType("uuid").HasColumnName("actor_identity_id");
            b.Property<string>("CommandKind").IsRequired().HasColumnType("text").HasColumnName("command_kind");
            b.Property<Guid>("TargetId").HasColumnType("uuid").HasColumnName("target_id");
            b.Property<string>("ExpectedOperationalName").IsRequired().HasColumnType("text").HasColumnName("expected_operational_name");
            b.Property<bool>("ExpectedIsActive").HasColumnType("boolean").HasColumnName("expected_is_active");
            b.Property<string>("NewOperationalName").HasColumnType("text").HasColumnName("new_operational_name");
            b.Property<string>("ResultOperationalName").IsRequired().HasColumnType("text").HasColumnName("result_operational_name");
            b.Property<bool>("ResultIsActive").HasColumnType("boolean").HasColumnName("result_is_active");
            b.Property<bool>("ResultIsDeleted").HasColumnType("boolean").HasColumnName("result_is_deleted");
            b.HasKey("IdempotencyKey");
            b.ToTable("preparation_responsibility_lifecycle_commands", "operational_configuration", t => t.HasCheckConstraint("CK_preparation_responsibility_lifecycle_commands_kind", "command_kind IN ('Rename', 'Retire', 'Reactivate', 'Delete')"));
        });
#pragma warning restore 612, 618
    }
}
