// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoBar.Inventory;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260901073703_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoBar.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CurrentRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("current_registered_quantity");

                    b.Property<long>("MovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_revision");

                    b.Property<string>("NormalizedOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_operational_name");

                    b.Property<string>("OperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operational_name");

                    b.Property<string>("OperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operational_unit");

                    b.HasKey("Id")
                        .HasName("PK_inventory_items");

                    b.HasIndex("NormalizedOperationalName")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_items_normalized_name");

                    b.ToTable("inventory_items", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_items_name_valid", "length(operational_name) BETWEEN 1 AND 200 AND operational_name = btrim(operational_name) AND position(chr(10) in operational_name) = 0 AND position(chr(13) in operational_name) = 0");

                            t.HasCheckConstraint("CK_inventory_items_revision_non_negative", "movement_revision >= 0");

                            t.HasCheckConstraint("CK_inventory_items_unit_valid", "length(operational_unit) BETWEEN 1 AND 100 AND operational_unit = btrim(operational_unit) AND position(chr(10) in operational_unit) = 0 AND position(chr(13) in operational_unit) = 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryItemCreationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_kind");

                    b.Property<string>("IntentNormalizedOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("intent_normalized_operational_name");

                    b.Property<string>("IntentOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intent_operational_unit");

                    b.Property<decimal?>("ResultCurrentRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("result_current_registered_quantity");

                    b.Property<Guid>("ResultItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_item_id");

                    b.Property<long>("ResultMovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_movement_revision");

                    b.Property<string>("ResultOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result_operational_name");

                    b.Property<string>("ResultOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_operational_unit");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_inventory_item_creation_commands");

                    b.HasIndex("ResultItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_item_commands_result_item");

                    b.ToTable("item_creation_commands", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_item_commands_kind", "command_kind = 'CreateInventoryItem'");

                            t.HasCheckConstraint("CK_inventory_item_commands_revision", "result_movement_revision >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryItemCreationCommand", b =>
                {
                    b.HasOne("NexoBar.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_item_commands_item");
                });
#pragma warning restore 612, 618
        }
    }
}
