// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoBar.Inventory;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoBar.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260901090459_AddInventoryCountReconciliation")]
    partial class AddInventoryCountReconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoBar.Inventory.CountObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<long>("ObservedMovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_movement_revision");

                    b.Property<string>("ObservedOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("observed_operational_unit");

                    b.Property<decimal>("ObservedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("observed_quantity");

                    b.HasKey("Id")
                        .HasName("PK_count_observations");

                    b.HasIndex("InventoryItemId", "ObservedAt")
                        .HasDatabaseName("IX_count_observations_item_observed_at");

                    b.ToTable("count_observations", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_count_observations_quantity_non_negative", "observed_quantity >= 0");

                            t.HasCheckConstraint("CK_count_observations_revision_non_negative", "observed_movement_revision >= 0");

                            t.HasCheckConstraint("CK_count_observations_unit_valid", "length(observed_operational_unit) BETWEEN 1 AND 100 AND observed_operational_unit = btrim(observed_operational_unit) AND position(chr(10) in observed_operational_unit) = 0 AND position(chr(13) in observed_operational_unit) = 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryCountCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_kind");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<decimal>("ObservedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("observed_quantity");

                    b.Property<Guid>("ResultCountObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_count_observation_id");

                    b.Property<DateTimeOffset>("ResultObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_observed_at");

                    b.Property<long>("ResultObservedMovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_observed_movement_revision");

                    b.Property<string>("ResultObservedOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_observed_operational_unit");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_count_commands");

                    b.HasIndex("ResultCountObservationId")
                        .IsUnique()
                        .HasDatabaseName("UX_count_commands_result_observation");

                    b.ToTable("count_commands", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_count_commands_kind", "command_kind = 'RecordInventoryCount'");

                            t.HasCheckConstraint("CK_count_commands_quantity_non_negative", "observed_quantity >= 0");

                            t.HasCheckConstraint("CK_count_commands_revision_non_negative", "result_observed_movement_revision >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CurrentRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("current_registered_quantity");

                    b.Property<long>("MovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_revision");

                    b.Property<string>("NormalizedOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_operational_name");

                    b.Property<string>("OperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operational_name");

                    b.Property<string>("OperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operational_unit");

                    b.HasKey("Id")
                        .HasName("PK_inventory_items");

                    b.HasIndex("NormalizedOperationalName")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_items_normalized_name");

                    b.ToTable("inventory_items", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_items_name_valid", "length(operational_name) BETWEEN 1 AND 200 AND operational_name = btrim(operational_name) AND position(chr(10) in operational_name) = 0 AND position(chr(13) in operational_name) = 0");

                            t.HasCheckConstraint("CK_inventory_items_revision_non_negative", "movement_revision >= 0");

                            t.HasCheckConstraint("CK_inventory_items_unit_valid", "length(operational_unit) BETWEEN 1 AND 100 AND operational_unit = btrim(operational_unit) AND position(chr(10) in operational_unit) = 0 AND position(chr(13) in operational_unit) = 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryItemCreationCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_kind");

                    b.Property<string>("IntentNormalizedOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("intent_normalized_operational_name");

                    b.Property<string>("IntentOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intent_operational_unit");

                    b.Property<decimal?>("ResultCurrentRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("result_current_registered_quantity");

                    b.Property<Guid>("ResultItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_item_id");

                    b.Property<long>("ResultMovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_movement_revision");

                    b.Property<string>("ResultOperationalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result_operational_name");

                    b.Property<string>("ResultOperationalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_operational_unit");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_inventory_item_creation_commands");

                    b.HasIndex("ResultItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_item_commands_result_item");

                    b.ToTable("item_creation_commands", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_item_commands_kind", "command_kind = 'CreateInventoryItem'");

                            t.HasCheckConstraint("CK_inventory_item_commands_revision", "result_movement_revision >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<Guid?>("CountObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("count_observation_id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<long>("MovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("movement_revision");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("nature");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal?>("PreviousRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("previous_registered_quantity");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ResultingRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("resulting_registered_quantity");

                    b.HasKey("Id")
                        .HasName("PK_inventory_movements");

                    b.HasIndex("CountObservationId")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_movements_count_observation")
                        .HasFilter("count_observation_id IS NOT NULL");

                    b.HasIndex("InventoryItemId", "MovementRevision")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_movements_item_revision");

                    b.ToTable("inventory_movements", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_movements_nature", "nature IN ('Reconciliation', 'Entry', 'ManualExit', 'Waste', 'Correction')");

                            t.HasCheckConstraint("CK_inventory_movements_reconciliation_count", "nature <> 'Reconciliation' OR count_observation_id IS NOT NULL");

                            t.HasCheckConstraint("CK_inventory_movements_reconciliation_quantity", "nature <> 'Reconciliation' OR quantity >= 0");

                            t.HasCheckConstraint("CK_inventory_movements_revision_positive", "movement_revision > 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryMovementCommand", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ActorIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identity_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_kind");

                    b.Property<Guid>("CountObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("count_observation_id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<Guid?>("ResultMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_movement_id");

                    b.Property<long>("ResultMovementRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_movement_revision");

                    b.Property<decimal>("ResultObservedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("result_observed_quantity");

                    b.Property<DateTimeOffset?>("ResultOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("result_occurred_at");

                    b.Property<string>("ResultOutcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("result_outcome");

                    b.Property<decimal?>("ResultPreviousRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("result_previous_registered_quantity");

                    b.Property<decimal>("ResultResultingRegisteredQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("result_resulting_registered_quantity");

                    b.HasKey("IdempotencyKey")
                        .HasName("PK_movement_commands");

                    b.HasIndex("CountObservationId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ResultMovementId")
                        .IsUnique()
                        .HasDatabaseName("UX_movement_commands_result_movement")
                        .HasFilter("result_movement_id IS NOT NULL");

                    b.ToTable("movement_commands", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_movement_commands_kind", "command_kind = 'ReconcileInventoryCount'");

                            t.HasCheckConstraint("CK_movement_commands_outcome", "result_outcome IN ('reconciled', 'no_discrepancy')");

                            t.HasCheckConstraint("CK_movement_commands_result_shape", "(result_outcome = 'reconciled' AND result_movement_id IS NOT NULL AND result_occurred_at IS NOT NULL) OR (result_outcome = 'no_discrepancy' AND result_movement_id IS NULL AND result_occurred_at IS NULL AND result_previous_registered_quantity = result_observed_quantity AND result_observed_quantity = result_resulting_registered_quantity)");

                            t.HasCheckConstraint("CK_movement_commands_revision_non_negative", "result_movement_revision >= 0");
                        });
                });

            modelBuilder.Entity("NexoBar.Inventory.CountObservation", b =>
                {
                    b.HasOne("NexoBar.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_count_observations_item");
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryCountCommand", b =>
                {
                    b.HasOne("NexoBar.Inventory.CountObservation", null)
                        .WithMany()
                        .HasForeignKey("ResultCountObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_count_commands_observation");
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryItemCreationCommand", b =>
                {
                    b.HasOne("NexoBar.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_item_commands_item");
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("NexoBar.Inventory.CountObservation", null)
                        .WithMany()
                        .HasForeignKey("CountObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_inventory_movements_count_observation");

                    b.HasOne("NexoBar.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_movements_item");
                });

            modelBuilder.Entity("NexoBar.Inventory.InventoryMovementCommand", b =>
                {
                    b.HasOne("NexoBar.Inventory.CountObservation", null)
                        .WithMany()
                        .HasForeignKey("CountObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_movement_commands_observation");

                    b.HasOne("NexoBar.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_movement_commands_item");

                    b.HasOne("NexoBar.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("ResultMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_movement_commands_movement");
                });
#pragma warning restore 612, 618
        }
    }
}
