<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexoBar.OperationalConfiguration\NexoBar.OperationalConfiguration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NexoBar.E2E.DatabaseSetup" />
    <InternalsVisibleTo Include="NexoBar.IdentitiesAndCapabilities.IntegrationTests" />
    <InternalsVisibleTo Include="NexoBar.OrderOperations.IntegrationTests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
