import { beforeEach, describe, expect, it, vi } from "vitest";
import { getTerminalOrderHistory, TerminalHistoryContractError } from "./terminalOrderHistoryClient.ts";
import { OrderOperationsProblemError } from "./orderOperationsClient.ts";
const fetchMock = vi.fn<typeof fetch>();
const base = { orderId:"id", operationalReference:"exact/ref", termination:{type:"Closure",id:"t",occurredAt:"2026-01-01T00:00:00Z",actorIdentityId:"actor",pendingCompositionDiscarded:false}, finalContextId:"ctx", finalContextOperationalName:"Mesa", contextChanges:[], incorporations:[], liquidation:null, closure:{actorIdentityId:"actor",occurredAtUtc:"2026-01-01T00:00:00Z"}, completeCancellation:null };
beforeEach(() => { fetchMock.mockReset(); vi.stubGlobal("fetch", fetchMock); });
describe("terminal history client", () => {
 it("parses Closure and requests the exact encoded reference", async () => { fetchMock.mockResolvedValueOnce(new Response(JSON.stringify(base), {status:200})); await expect(getTerminalOrderHistory("exact/ref")).resolves.toMatchObject({operationalReference:"exact/ref"}); expect(fetchMock).toHaveBeenCalledWith("/api/order-operations/order-history/exact%2Fref", {credentials:"same-origin"}); });
 it("parses Complete Cancellation with nullable product name", async () => { const cancel = {...base, termination:{...base.termination,type:"CompleteCancellation"}, closure:null, completeCancellation:{actorIdentityId:"actor",occurredAtUtc:"2026-01-01T00:00:00Z",pendingCompositionDiscarded:true,consequences:[]}, incorporations:[{id:"inc",ordinal:1,confirmedAtUtc:"2025-12-31T00:00:00Z",actorIdentityId:"actor",confirmedContextId:"ctx",confirmedContext:"Mesa",contents:[{contentOrdinal:1,productId:"p",productOperationalNameSnapshot:null,originalConfirmedQuantity:1,appliedPrice:"10",instruction:null,requiresPreparation:false,preparationResponsibilityId:null,unavailableProductExceptionApplied:false,effectiveAppliedPrice:"10",priceCorrections:[],corrections:[],cancellations:[],removedByCorrectionQuantity:0,cancelledQuantity:0,deliveries:[],deliveryCorrections:[],effectiveDeliveredQuantity:0,preparationHistory:[]}]}]}; fetchMock.mockResolvedValueOnce(new Response(JSON.stringify(cancel), {status:200})); await expect(getTerminalOrderHistory("ref")).resolves.toMatchObject({termination:{type:"CompleteCancellation"}, incorporations:[{contents:[{productOperationalNameSnapshot:null}]}]}); });
 it("rejects malformed required fields", async () => { fetchMock.mockResolvedValueOnce(new Response(JSON.stringify({operationalReference:"ref"}), {status:200})); await expect(getTerminalOrderHistory("ref")).rejects.toBeInstanceOf(TerminalHistoryContractError); });
 it("uses ProblemDetails for unavailable history", async () => { fetchMock.mockResolvedValueOnce(new Response(JSON.stringify({code:"not_found"}), {status:404,headers:{"content-type":"application/problem+json"}})); await expect(getTerminalOrderHistory("ref")).rejects.toMatchObject({problem:{status:404,code:"not_found"}} satisfies Partial<OrderOperationsProblemError>); });
});
